src/main/java/com/goalapa/cacamuca/requestDomain/command/application/service/SaveRequestToFoodImpl.java, src/main/java/com/goalapa/cacamuca/requestDomain/command/domain/service/SaveRequestToFood.java
=> fix: class 추가

src/main/java/com/goalapa/cacamuca/blackListDomain/command/application/controller/Controller.java, src/main/java/com/goalapa/cacamuca/blackListDomain/command/application/dto/Dto.java, src/main/java/com/goalapa/cacamuca/blackListDomain/command/application/service/Service.java, src/main/java/com/goalapa/cacamuca/blackListDomain/command/domain/service/Service.java, src/main/java/com/goalapa/cacamuca/blackListDomain/command/infrasturcture/repository/Repository.java, src/main/java/com/goalapa/cacamuca/blackListDomain/command/infrasturcture/service/Service.java, src/main/java/com/goalapa/cacamuca/blackListDomain/query/application/controller/Controller.java, src/main/java/com/goalapa/cacamuca/blackListDomain/query/application/dto/Dto.java, src/main/java/com/goalapa/cacamuca/blackListDomain/query/application/service/Service.java, src/main/java/com/goalapa/cacamuca/blackListDomain/query/domain/entity/Entity.java, src/main/java/com/goalapa/cacamuca/blackListDomain/query/domain/service/Service.java, src/main/java/com/goalapa/cacamuca/blackListDomain/query/infrastructure/repository/Repository.java, src/main/java/com/goalapa/cacamuca/blackListDomain/query/infrastructure/service/Service.java, src/main/java/com/goalapa/cacamuca/reportDomain/command/application/controller/ReportController.java, src/main/java/com/goalapa/cacamuca/reportDomain/command/application/dto/ReportDeleteDTO.java, src/main/java/com/goalapa/cacamuca/reportDomain/command/application/service/ReportServiceImpl.java, src/main/java/com/goalapa/cacamuca/reportDomain/command/domain/aggregate/entity/BlackList.java, src/main/java/com/goalapa/cacamuca/reportDomain/command/domain/aggregate/entity/Blacklist.java, src/main/java/com/goalapa/cacamuca/reportDomain/command/domain/repository/BlackListRepository.java, src/main/java/com/goalapa/cacamuca/reportDomain/command/domain/service/ReportService.java, src/main/java/com/goalapa/cacamuca/reportDomain/query/application/controller/ReportQueryController.java, src/main/resources/mapper/ReportMapper.xml, src/main/resources/templates/report-page.html, src/main/resources/templates/reportAdminPage.html
* 블랙 리스트 도메인이 신고 컨텍스트에 포함되어있으므로 삭제
* 기존 블랙리스트 도메인에 있던 블랙 리스트 entity, repository를 신고 도메인으로 이동
* 신고 페이지의 버튼 디자인을 간단하게 수정
=> Feature/report : (#95) 블랙리스트 도메인 삭제/수정, 신고 페이지 디자인 수정

src/main/java/com/goalapa/cacamuca/foodDomain/command/application/dto/FoodDTO.java, src/main/java/com/goalapa/cacamuca/foodDomain/command/application/service/SaveFoodFromRequestImpl.java, src/main/java/com/goalapa/cacamuca/foodDomain/command/domain/aggregate/entity/Food.java, src/main/java/com/goalapa/cacamuca/foodDomain/command/domain/aggregate/vo/CountryVO.java, src/main/java/com/goalapa/cacamuca/foodDomain/command/domain/aggregate/vo/FoodTypeVO.java
=> Feature/food (#48) 식품 Entity, VO 추가 및 수정

src/main/java/com/goalapa/cacamuca/memberDomain/query/application/controller/QueryMemberController.java, src/main/java/com/goalapa/cacamuca/memberDomain/query/application/service/QueryMemberServiceImpl.java, src/main/java/com/goalapa/cacamuca/memberDomain/query/domain/aggregate/dto/MemberDTO.java, src/main/java/com/goalapa/cacamuca/memberDomain/query/domain/repository/MemberMapper.java, src/main/resources/db/data/data.sql, src/main/resources/mapper/MemberMapper.xml, src/main/resources/templates/adminList.html
#99 
회원목록조회 페이징, 정렬 추가
정렬은 오름차순만 구현되어있음.
=> Fix/member (#99)  [회원] 회원목록조회

src/main/java/com/goalapa/cacamuca/categoryDomain/command/application/controller/CategoryController.java, src/main/java/com/goalapa/cacamuca/categoryDomain/command/application/service/AddCategoryService.java, src/main/java/com/goalapa/cacamuca/categoryDomain/command/application/service/UpdateCategoryService.java, src/main/java/com/goalapa/cacamuca/categoryDomain/command/domain/repository/CategoryRepository.java, src/main/java/com/goalapa/cacamuca/categoryDomain/command/domain/service/CategoryService.java
=> #47 [카테고리] 카테고리 수정

.github/workflows/gradle.yml, src/main/resources/application-prod.yml
[[release] 배포(#131)](https://github.com/goalapa/spring-cacamuca/issues/131)
데이터베이스 유저, 패스워드 암호화
깃헙 액션 시크릿에 key, variable 저장 및 actions flow 정의
=> feat : github actions secret 환경설정

src/main/java/com/goalapa/cacamuca/appreviewDomain/query/application/service/FindAppReviewService.java, src/main/java/com/goalapa/cacamuca/foodDomain/command/application/controller/FoodController.java, src/main/java/com/goalapa/cacamuca/foodDomain/command/application/service/SaveFoodFromRequestImpl.java, src/main/java/com/goalapa/cacamuca/requestDomain/query/application/service/FindRequestPicService.java, src/main/java/com/goalapa/cacamuca/requestDomain/query/application/service/FindRequestService.java, src/main/java/com/goalapa/cacamuca/statDomain/command/application/controller/StatController.java, src/main/java/com/goalapa/cacamuca/statDomain/query/domain/respository/GetStatMapper.java, src/main/java/com/goalapa/cacamuca/statDomain/query/domain/service/GetStatService.java, src/main/resources/db/data/data.sql, src/main/resources/mapper/GetStatMapper.xml, src/main/resources/templates/adminAppRev.html, src/main/resources/templates/appReview.html, src/main/resources/templates/common/adminAside.html, src/main/resources/templates/mainCountry.html, src/main/resources/templates/request.html, src/main/resources/templates/requestDetail.html, src/main/resources/templates/requestList.html, src/main/resources/templates/stat-top10.html, src/main/resources/templates/stat.html, src/main/resources/templates/statDetail.html
통합 테스트 피드백 반영 및 통계 상세보기(일부) 추가
폰트 적용
-통계 전체 국가 조회 오류 생겨서 잠시 막아뒀습니다.
기본값 한국으로 되어있습니다.
=>  Feature/appreview 통합테스트 피드백 반영

src/main/java/com/goalapa/cacamuca/statDomain/command/application/controller/StatController.java, src/main/java/com/goalapa/cacamuca/statDomain/query/domain/respository/GetStatMapper.java, src/main/java/com/goalapa/cacamuca/statDomain/query/domain/service/GetStatService.java, src/main/resources/db/data/data.sql, src/main/resources/mapper/GetStatMapper.xml, src/main/resources/templates/appReview.html, src/main/resources/templates/statDetail.html
=> Feature/appreview (#176)

src/main/java/com/goalapa/cacamuca/reviewDomain/command/application/controller/ReviewController.java, src/main/java/com/goalapa/cacamuca/reviewDomain/command/application/service/ReviewService.java, src/main/java/com/goalapa/cacamuca/reviewDomain/command/domain/repository/ReviewPicRepository.java, src/main/resources/templates/review/reviewDetail.html
=> Feature/review [리뷰] 좋아요 및 신고 해결

src/main/java/com/goalapa/cacamuca/reviewDomain/command/application/controller/ReviewController.java, src/main/java/com/goalapa/cacamuca/reviewDomain/query/application/controller/SelectReviewController.java
=> feat : 리뷰 일부 페이지 로그아웃 상태에서 접근 불가

src/main/resources/db/data/data.sql
=> style: 공백제거

src/main/java/com/goalapa/cacamuca/requestDomain/command/application/controller/RequestController.java, src/main/java/com/goalapa/cacamuca/requestDomain/command/application/service/SaveRequestPicImpl.java, src/main/java/com/goalapa/cacamuca/requestDomain/command/domain/repository/RequestRepository.java, src/main/java/com/goalapa/cacamuca/requestDomain/command/domain/service/SaveRequestPic.java
=> fix: requestPic 수정

src/main/resources/db/data/ddl.sql
=> github actions 테스트 자동화

src/main/java/com/goalapa/cacamuca/foodDomain/command/domain/repository/FoodRepository.java, src/main/java/com/goalapa/cacamuca/reviewDomain/command/application/controller/ReviewController.java, src/main/java/com/goalapa/cacamuca/reviewDomain/command/application/dto/ReviewDTO.java, src/main/java/com/goalapa/cacamuca/reviewDomain/command/application/service/ReviewService.java, src/main/java/com/goalapa/cacamuca/reviewDomain/command/infrastructure/service/ReviewValidationServiceImpl.java, src/main/java/com/goalapa/cacamuca/reviewDomain/query/application/controller/SelectReviewController.java, src/main/resources/db/data/data.sql, src/main/resources/templates/review.html, src/main/resources/templates/review/selectReviews.html, src/test/java/com/goalapa/cacamuca/reviewDomain/command/application/controller/Object/TestObjects.java, src/test/java/com/goalapa/cacamuca/reviewDomain/command/application/controller/ReviewController.java
This reverts commit 0af0974a682782f8ac6c97771ca136939c8d3d3a.
#200 
정렬 순서 변경 및 사진 미업로드 저장 기능 추가
=> feat : (#200) 정렬 순서 변경 및 사진 미업로드 저장 기능 추가

src/main/java/com/goalapa/cacamuca/categoryDomain/command/application/controller/CategoryController.java, src/main/resources/application-prod.yml, src/main/resources/application.yml, src/main/resources/db/data/ddl.sql, src/main/resources/mapper/FoodRegistMapper.xml, src/test/java/com/goalapa/cacamuca/memberDomain/query/application/controller/QueryMemberControllerTest.java, src/test/java/com/goalapa/cacamuca/memberDomain/query/application/service/WithMockUserTests.java, src/test/java/com/goalapa/cacamuca/reportDomain/command/application/service/ReportServiceTests.java
=> Feature/report create [신고] 테스트 버그 수정

src/main/java/com/goalapa/cacamuca/requestDomain/command/application/controller/RequestController.java, src/main/java/com/goalapa/cacamuca/requestDomain/command/application/service/SaveRequestImpl.java, src/main/java/com/goalapa/cacamuca/requestDomain/command/domain/aggregate/entity/RequestPic.java, src/main/java/com/goalapa/cacamuca/requestDomain/command/domain/service/SaveRequest.java, src/main/resources/db/data/data.sql, src/main/resources/templates/main.html, src/main/resources/templates/stat-top10.html
- data.sql 수정
- selectbox 국가 이름 수정
=> Feature/appreview 수정

src/main/resources/db/data/data.sql, src/test/java/com/goalapa/cacamuca/reportDomain/command/application/service/ReportServiceTests.java
Member와 loginMember 반대로 되어있던 부분 수정
=> ReviewController 버그 수정

src/main/java/com/goalapa/cacamuca/reviewDomain/query/application/service/SelectReviewService.java, src/main/resources/application.yml, src/main/resources/db/data/data.sql, src/main/resources/mapper/ReviewMapper.xml, src/main/resources/templates/review/search.html, src/main/resources/templates/review/selectReviews.html
=> fix : 페이지 내 좋아요 수 추가

src/main/resources/db/data/data.sql
=> fix : sql문 수정(통계 데이터)

src/main/resources/db/data/data.sql
=> fix: data.sql 수정

src/main/resources/db/data/data.sql, src/main/resources/mapper/ReviewMapper.xml
=> fix : review data 추가

.github/workflows/gradle.yml
=> refactor : git actions, yml 생성 job 추가

README.md, src/main/java/com/goalapa/cacamuca/memberDomain/command/application/service/CommandMemberServiceImpl.java, src/main/java/com/goalapa/cacamuca/reportDomain/command/application/service/ReportServiceImpl.java, src/main/java/com/goalapa/cacamuca/reviewDomain/command/domain/repository/ReviewPicRepository.java, src/main/java/com/goalapa/cacamuca/reviewDomain/query/application/controller/SelectReviewController.java, src/main/java/com/goalapa/cacamuca/statDomain/command/application/service/StatScheduler.java, src/main/resources/db/data/data.sql, src/main/resources/templates/member/findId.html, src/main/resources/templates/member/findPassword.html, src/test/java/com/goalapa/cacamuca/memberDomain/command/application/controller/CommandMemberControllerTest.java
Reverts goalapa/spring-cacamuca#227
=> Revert "refactor yml 파일 제거"

.github/workflows/gradle.yml
Reverts goalapa/spring-cacamuca#233
=> Revert "Refactor/225"

.github/workflows/gradle.yml
=> Feat github actions job 설정 변경
